server:
  port: 84

spring:
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms
  application:
    name: consumer-order
  cloud:
    zookeeper:
      connect-string: zhoushiya-centos7:2181