server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 开启服务发现，下面使用微服务名称进行调用
      discovery:
        locator:
          enabled: true
      routes:
          # 路由器 ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          # 匹配后提供服务的路由地址
          # uri: http://localhost:8001
          # 匹配后提的微服务地址(lb表示负载均衡)
          uri: lb://provider-payment
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://provider-payment
          predicates:
            - Path=/payment/waitTime/{millis}
          filters:
            # 添加参数waitTime，值与millis相同
            - AddRequestParameter=waitTime,{millis}
        - id: payment_routh3
          uri: lb://provider-payment
          predicates:
            # 时间必须大于
            - After=2020-09-29T18:06:00.000+08:00[Asia/Shanghai]
            # 时间必须小于
            - Before=2999-09-29T18:06:00.000+08:00[Asia/Shanghai]
            # api地址限定
            - Path=/payment/uuid
            # 包含cookie，名称为username，值为zhoushiya
            - Cookie=username,zhoushiya
            # 包含header头，token，值为123456
            - Header=token,123456
            # URL主机地址为localhost
            #- Host=localhost,127.0.0.1
            # 支持Get访问
            - Method=GET
            # 必须带有参数green
            - Query=green
            # 客户端地址限定
            #- RemoteAddr=localhost

eureka:
  client:
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
  instance:
    # 修改实例id
    instance-id: gateway9527
    # 访问IP以路径显示
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，单位秒（默认30秒）
    lease-expiration-duration-in-seconds: 1
