server:
  port: 8002

spring:
  application:
    name: provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=GMT%2B8
    username: root
    password: welcome
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有实体的目录
  type-aliases-package: com.zhoushiya.springcloud.entities

eureka:
  client:
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true