server:
  port: 81

spring:
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms
  application:
    name: consumer-order

eureka:
  client:
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
  instance:
    # 修改实例id
    instance-id: order81
    # 访问IP以路径显示
    prefer-ip-address: true