server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=GMT%2B8
    username: root
    password: welcome
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms
  cloud:
    zookeeper:
      # 服务地址
      connect-string: zhoushiya-centos7:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有实体的目录
  type-aliases-package: com.zhoushiya.springcloud.entities

