server:
  port: 10001

spring:
  application:
    name: provider-payment
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms
  cloud:
    # nacos配置
    nacos:
      discovery:
        # 尝试使用centos集群版地址
        server-addr: zhoushiya-centos7:1111
        # 本机的地址
        #server-addr: localhost:8848

# 监控端点全部打开
management:
  endpoints:
    web:
      exposure:
        include: "*"
