server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  devtools:
    restart:
      # 修复热启动失效的问题
      poll-interval: 1000ms
      quiet-period: 999ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"
